#!/usr/bin/env bash
set -ue

if [ $# -eq 0 ]; then
  ACTION=$(
         cat << EOF | fzf --prompt="gh gist > " --height=40%
clone
delete
edit
view
EOF
  )
  if [ $? -ne 0 ]; then
      exit 1
  fi
else
  ACTION=$1
fi

GIST=$(gh gist list --limit 50 | fzf --prompt="gh gist $ACTION > " --height=40% | awk '{print $1}')

if [ -z $GIST ]; then
    exit 1
fi

gh gist $ACTION $GIST
