#!/usr/bin/env bash
set -ue

ACTION=$(cat << EOF | fzf
clone
delete
edit
view
EOF
)

if [ $? -ne 0 ]; then
    exit 1
fi

GIST=$(gh gist list | fzf --prompt="gh gist $ACTION > " | awk '{print $1}')

if [ $GIST -z ]; then
    exit 1
fi

gh gist $ACTION "$GIST"
